## WHY USE NUMPY?

NumPy provides efficient storage

It also provides better ways of handling data for processing

It is fast

It is easy to learn

NumPy uses relatively less memory to store data

## JUPYTER NOTEBOOK

The Jupyter Notebook is an open-source web application that allows you to create
and share documents that contain live code, equations, visualizations and narrative
text.

The Notebook has support for over 40 programming languages, including Python, R,
Julia, and Scala.

 Notebooks can be shared with others using email, Dropbox, GitHub and the Jupyter
Notebook Viewer.

 Your code can produce rich, interactive output: HTML, images, videos, LaTeX, and
custom MIME types.

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,37,7],np.int8)  
#it meant 8 bit int is used here 
# greater than 8 bit number will not be supported 
myarr

array([ 3,  6, 37,  7], dtype=int8)

In [3]:
myarr[0] #as 1d array it is 

3

In [4]:
myarr1=np.array([[3,6,37,7]],np.int64)
myarr1[0,1] # 0th row and 1st column

6

In [5]:
print(myarr1.shape)
print(myarr.shape)

(1, 4)
(4,)


In [6]:
print(myarr.dtype)
print(myarr1.dtype)

int8
int64


In [7]:
myarr1[0,1]=45 #element can be updated in it 
myarr1

array([[ 3, 45, 37,  7]])

## There are 5 general mechanisms for creating arrays:
1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)

## Conversion from other Python structures (e.g., lists, tuples)

In [8]:
listarray=np.array([[1,2,3],[5,8,5],[0,8,3]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 8, 3]])

In [10]:
print(listarray.dtype)
print(listarray.shape)
print(listarray.size)


int64
(3, 3)
9


In [11]:
np.array({34,23,21}) ## dictionary

array({34, 21, 23}, dtype=object)

## Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [12]:
zeros=np.zeros((2,5)) #giving numpy array of size 2 having 5 zeroes in each
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#arange
rng=np.arange(15) # give continuous from 0 to 14 in an numpy array 
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
#linspace
lspace=np.linspace(1,50,10) # 10 elements of equally space from 1 to 50
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [15]:
lspace1=np.linspace(1,4,4)  # 4 elements of equally space from 1 to 4
lspace1

array([1., 2., 3., 4.])

In [16]:
# empty [it provides the numpy array providing random values]
emp1=np.empty((4,6)) # here a numpy array of random values of 0 in 4 cross 6 numpy array
emp1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
#if i want to have an empty array having element like before i have created any array 
# empty_like
emp_like=np.empty_like(lspace1) # elements in lspace1 will be put under emp_like
emp_like

array([1., 2., 3., 4.])

In [18]:
#providing identity matrix of size mentioned  like here of 45
ide=np.identity(45) 
print(ide)
print(ide.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(45, 45)


In [19]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [20]:
arr=arr.reshape(9,11)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [23]:
# now if i want it again to get correct then
# ravel()
arr=arr.ravel()
## if i without assigning content to arr directly want to have output with arr it will return the previous one arr 
## content so to update it i will have to assign this
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
arr.shape

(99,)

## numpy axis
axis=0 [rows]
axis=1 [columns]

In [26]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar # 2d array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [27]:
ar.sum(axis=0) # given sum of rows 

array([12,  8,  9])

In [29]:
ar.sum(axis=1) # gives sum of columns

array([ 6, 15,  8])

In [30]:
ar.T #transposing the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [33]:
# it functions like iterator 
# like this it can be printed
ite=ar.flat
for item in ite:
    print(item)
    

1
2
3
4
5
6
7
1
0


In [34]:
#to find dimenssion of our array 
ar.ndim

2

In [38]:
# to find array size
ar.size

9

In [36]:
# to find no. of bytes the ar taking
ar.nbytes # 9*8=72

72

In [39]:
## without () is used then it is an attribute 
## but if with () is used then it is function
one=np.array([1,3,4,634,2])

In [41]:
# Argmax is an operation that finds the argument that gives the maximum value from a target function.
# providing index for which the the function providing max value
one.argmax()

3

In [44]:
# providing the indexes after sorting it  in ascending form 
one.argsort()

array([0, 4, 1, 2, 3])

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
print(ar.argmin())
print(ar.argmax())
print(ar.argmax(axis=0))
print(ar.argmax(axis=1))


8
6
[2 1 1]
[2 2 0]


In [48]:
ar.argsort(axis=1)


array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [49]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [51]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar2=np.array([[1,2,1],
            [4,0,6],
            [8,1,0]])
print(ar+ar2)
print(ar*ar2)
print(np.sqrt(ar2))
## this addition is possible with numpy 

[[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]
[[ 1  4  3]
 [16  0 36]
 [56  1  0]]
[[1.         1.41421356 1.        ]
 [2.         0.         2.44948974]
 [2.82842712 1.         0.        ]]


In [56]:
# but with list it would not be possible
[324,34]+[34,526] # it just conctenate but not do addition of elements

[324, 34, 34, 526]

In [59]:
## similarly such more functions are 
print(ar.min())
print(ar.max())
print(ar.sum())

0
7
29


In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [62]:
type(np.where(ar>5))

tuple

In [63]:
## finding no. of non zeros in array
np.count_nonzero(ar)

8

In [64]:
np.nonzero(ar)
# (array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))
# 1st array showing index of row and other one showing index of column

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [66]:
ar[1,2]=0
np.nonzero(ar) ## ar[1,2] will not be available
# it will provide tuple for each axis seperately

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [71]:
#. It lets us access system-specific parameters and functions

import sys 

 simple python array takes a lot more storage hence make process much slower 
 while numpy makes it faster as it just take as much it requires the space so it just fasts the process 

In [77]:
py_ar=[0,4,55,2]
np_ar=np.array(py_ar)
print(type(py_ar))
print(type(np_ar))

<class 'list'>
<class 'numpy.ndarray'>


In [74]:
# telling size of an element [sys.getsizeof(1)] 
sys.getsizeof(1)*len(py_ar)

112

In [75]:
np_ar.itemsize*np_ar.size

32

 ## This is how numpy is used in vast as compared to simple array 
 
 so if want to know more functions and attributes of it just google as per the requirements 